### ISSUE TITLE
Lambda Layers size exceeded error on v3.1.5 update from v3.1.0

### ISSUE THREAD

**Issue by benb1n** [aws-solutions-library-samples/guidance-for-media2cloud-on-aws#41]
**Describe the bug**
The v3.1.5 update failed to deploy the backend stack due to an issue with the ImageProcessLayer for the IngestImageLambda. I received this error in CloudFormation:

> Layers consume more than the available size of 262144000 bytes

To work around the error, I commented out this layer for the IngestImageLambda function and was able to deploy it. I don't use image processing at the moment, so that works for me for now.

**To Reproduce**
1. Merge in the latest changes to my fork from the upstream. I was previously using v3.1.0.
2. Run the batch scripts to build and deploy the CloudFormation files.
3. Update the stack from the CloudFormation template.

**Expected behavior**
I would expect it to update without issues.

**Please complete the following information about the solution:**
- [x] Version: [e.g. v3.0.0] - 3.1.5
- [x] Region: [e.g. us-east-1] - us-east-1
- [x] Was the solution modified from the version published on this repository? Yes, but only slightly and not related to any Lambda functions or layers.
- [x] If the answer to the previous question was yes, are the changes available on GitHub? yes - https://github.com/DashMR/media2cloud-on-aws
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No, but this isn't a service limit issue.
- [x] Were there any errors in the CloudWatch Logs? No, it's a CloudFormation deployment issue.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by dorianva** [comment]
Hello! just noting that my team is facing this issue as well deploying 3.1.5 from resources built and deployed to a custom bucket (single region, west-2). Getting an error while creating the stack: "Layers consume more than the available size of 262144000 bytes" during the creation of IngestImageLambda. 

We do use image processing and would like to know what the ETA is for this fix, if possible. Thank you!

**Comment by aws-kens** [comment]
Hi @dorianva and @benb1n,

Thanks for reporting the issue.
We are testing a fix that will reduce the image processing layer size.

**Comment by aws-kens** [comment]
Hi @dorianva and @benb1n,

The root cause of the lambda layer size is due to the peerDependencies of the aws-elasticsearch-connector package. The bugfix is to move the aws-elasticsearch-connector package from core-lib layer to aws-sdk layer.

Please pull the latest code and rebuild.
