### ISSUE TITLE
Parameter Missing from Tutorial

### ISSUE THREAD

**Issue by big-zack** [aws-solutions-library-samples/guidance-for-media2cloud-on-aws#49]
---
name: Parameter Missing from Tutorial #49
about: Create a report to help us improve
title: ''
labels: issue
assignees: ''

---

**Describe the bug**
Cloud Formation Stack Fails because of "Compatibility Check" needs to be acknowledged. 

**To Reproduce**
Using the tutorial inputs alone leads to a Rollback on the Cloud Formation. I added this flag to the deployment. IMO this should be baked into the Tutorial Steps. 

 ` "ParameterKey=VersionCompatibilityStatement,ParameterValue=\"Yes, I understand and proceed\"" \ `

**Expected behavior**
Once this statement has been added the Cloud Formation deploys correctly. 

**Please complete the following information about the solution:**
- [ ] Version:  v4.0.0]
- [ ] Region: [e.g. us-west-2]
- [ ] Were there any errors in the CloudWatch Logs?

Line 161 of the Media2Cloud.Termplate

    _VersionCompatibilityStatement:
        Type: String
        Description: The new Version 4 of Media2Cloud is not compatible with previous versions due to several optimization changes. These changes include the Amazon OpenSearch cluster indexes and consolidation of the generated metadata. While a migration tool is being developed to help customers migrate from previous versions to Version 4, this CloudFormation template SHOULD NOT be used to update your existing Media2Cloud V3 deployment to the latest version. Confirm that you have read and understand the version compatibility statement. If you are creating a new stack, select "Yes, I understand and proceed".
        Default: No, do not proceed
        AllowedValues:
            - Yes, I understand and proceed
            - No, do not proceed_

**Comment by aws-kens** [comment]
Hi @big-zack ,

Thanks for reporting the issue.
For Installation, please follow the instruction in [Installation](https://github.com/aws-solutions-library-samples/guidance-for-media2cloud-on-aws?tab=readme-ov-file#installation) section

For using the RESTful API programmatically, please follow the [API documentation](https://github.com/aws-solutions-library-samples/guidance-for-media2cloud-on-aws/blob/main/source/api/README.md)

Thanks
