### ISSUE TITLE
Deployment into eu-west-3 fails

### ISSUE THREAD

**Issue by daniel-pebble** [aws-solutions-library-samples/guidance-for-media2cloud-on-aws#55]
**Describe the bug**
I attempted to deploy this stack in eu-west-3 but it fails, I'm guessing because rekognition isn't available in this region.
https://console.aws.amazon.com/cloudformation/home?region=eu-west-3#/stacks/quickcreate?templateURL=https://awsi-megs-guidances-eu-west-3.s3.eu-west-3.amazonaws.com/media2cloud/latest/media2cloud.template&stackName=media2cloudv4

Received response status [FAILED] from custom resource. Message returned: getaddrinfo ENOTFOUND rekognition.eu-west-3.amazonaws.com. 

**To Reproduce**
Deploy stack in eu-west-3

**Expected behavior**

**Comment by aws-kens** [comment]
Hi @daniel-pebble ,

Thanks for reporting the issue. You are correct that Amazon Rekognition is currently not supported in Paris (eu-west-3) region and Media2Cloud does rely on the Amazon Rekognition service.

We have removed the pre-built template for Paris region.

A workaround is to create the CFN stack on Ireland (eu-west-1) region. For trying out the Generative AI feature, specify `Paris [Europe] (eu-west-3)` in the _Generative AI with Amazon Bedrock service_ field. This would mean that the inference requests are sent to the Paris region. Also note that there will be cost incurred for Data transfer out of the Ireland (eu-west-1) region.
